### ISSUE TITLE
08/11|issueの練習(梅原)

### ISSUE THREAD

**Issue by umepon0626** [miraiproject/hatano.chore#1]
issue

## Confirm Deadline(期限)

**Will you be able to keep the deadline(期限を守れますか？)**

- [x] YES
- [ ] NO

**If you chose "NO", why is that? (もしできないのならなぜですか？)**

**Did you ask さん or さん about the deadline if you can't keep it or postpone it? (期限を守れなかったり、延期するときはさんかさんに連絡・相談しましたか？)**

- [ ] YES
- [ ] NO

**If you chose "NO", how will you update this? (もしできなかったらどうアップデートしますか？)**

## Task Description (タスク詳細)

**Problem to solve (どんな問題があるか):**
タスクのフローがわからない
**Solution (解決策):**
実際にタスクのフローをしてみる
**Time estimated to complete (完了推定時間):**
5m

## Task checklist (タスクチェックリスト)
- [ ] ブランチを切る。
- [ ] 作業する
- [ ] プッシュしてPR
## Checklist to complete before closing the issue (イシューを閉じる前のチェックリスト)

- [ ] Label `WIP` has been unset (`WIP`ラベルが設定されていないか)
- [ ] Notify coworkers if they need to take specific actions following your
  merge in master
- [ ] Overview written (Overviewを記入する)
- [ ] [Evaluation form](https://goo.gl/forms/J3Dc4pMKPefURskw1) with
  CTO evaluation scores.

## Overview

**Investigation time (調査時間）：**
**Implementation time (実装時間）：**
